# Generated by Django 6.0.4 on 2026-04-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('occupancy_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('is_balcony_room', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('sleep_schedule', models.CharField(help_text='e.g., Early Bird, Night Owl', max_length=100)),
                ('dietary_preference', models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non-Veg'), ('vegan', 'Vegan')], default='veg', max_length=20)),
                ('balcony_preference', models.BooleanField(default=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority_score', models.IntegerField(default=1, help_text='1 (Low) to 5 (High)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.student')),
            ],
        ),
    ]
