# Generated by Django 6.0.4 on 2026-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_status_complaint_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
