# Generated by Django 6.0.4 on 2026-04-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_capacity_alter_student_name_bed_student_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_staff',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
