# Generated by Django 6.0.4 on 2026-04-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_complaint_ai_summary_complaint_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=20),
        ),
    ]
